import {MeshoptDecoder} from './assets/vendor/meshopt_decoder.module.js';
import * as THREE from 'three';
import {OrbitControls} from './assets/vendor/OrbitControls.js';
import {GLTFLoader} from './assets/vendor/GLTFLoader.js';
export function mountScenes(root, scenes, models, augmentation=false){
 let scene=scenes[0], variant=scene.variants[0], backend='blender', active=0, cameraIndex=0, time=0, playing=false, generation=0, object=null;
 const el=(tag,cls,text)=>{let e=document.createElement(tag);e.className=cls||'';if(text)e.textContent=text;return e};
 const pick=el('div','scene-picker'),variants=el('div','variant-picker'),shell=el('div','demo-shell');root.append(pick,variants,shell);
 const top=el('div','demo-top'),title=el('h3'),prompt=el('p','scene-prompt');top.append(title);shell.append(top,prompt);
 const grid=el('div','scene-grid'),left=el('div','world-panel'),right=el('div','camera-panel');grid.append(left,right);shell.append(grid);
 const head=el('div','panel-heading'),toggle=el('div','segmented');head.append(el('span','','3D scene'),toggle);left.append(head);
 const modelButtons={};for(const kind of ['blender','mujoco']){let b=el('button','',kind==='blender'?'Blender':'MuJoCo');b.onclick=()=>{backend=kind;loadModel()};toggle.append(b);modelButtons[kind]=b}
 const world=el('div','world-canvas'),status=el('div','world-status','Loading 3D scene…');world.append(status);left.append(world);
 const foot=el('div','world-footer'),reset=el('button','','Reset view');foot.append(el('span','','Drag to orbit · Scroll to zoom'),reset);left.append(foot);
 const cameraHead=el('div','panel-heading'),mode=el('select');mode.setAttribute('aria-label','Video camera view');cameraHead.append(el('span','','Multi-view video'),mode);right.append(cameraHead);
 const cams=el('div','camera-grid');right.append(cams);right.append(el('div','world-footer video-footer','Click a smaller video to enlarge'));
 const toolbar=el('div','playback'),play=el('button','','▶ Play'),range=el('input'),clock=el('span','','0:00');range.type='range';range.min=0;range.max=1;range.step=.001;range.value=0;toolbar.append(play,range,clock);shell.append(toolbar);
 root.append(el('p','demo-note',augmentation?'Rotate the 3D scene on the left. Choose one camera to compare Real RGB, Blender RGB and MuJoCo RGB on the right; click a smaller video to enlarge it. Real RGB is the original reference.':'Rotate Blender or MuJoCo geometry on the left. Choose one camera to compare aligned Real RGB, Blender RGB and MuJoCo RGB on the right; click a smaller video to enlarge it.'));
 let inView=false,needsModel=true,renderDirty=true;new IntersectionObserver(es=>{inView=es[0].isIntersecting;if(inView)renderDirty=true;if(inView&&needsModel){needsModel=false;loadModel()}},{rootMargin:'200px'}).observe(world);let renderer,controls,camera,worldScene;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeff2eb);renderer.outputColorSpace=THREE.SRGBColorSpace;world.append(renderer.domElement);worldScene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.001,1000);camera.up.set(0,1,0);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.addEventListener('change',()=>{renderDirty=true});worldScene.add(new THREE.HemisphereLight(0xffffff,0x8a9686,2));let l=new THREE.DirectionalLight(0xffffff,2);l.position.set(3,-2,5);worldScene.add(l);new ResizeObserver(()=>{let w=world.clientWidth,h=world.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();renderDirty=true}).observe(world);renderer.setAnimationLoop(()=>{if(inView){controls.update();if(renderDirty){renderer.render(worldScene,camera);renderDirty=false}}})}catch(e){status.textContent='3D display requires WebGL in your browser.'}
 let home;function fit(){if(!object)return;const hint=modelEntry()?.view_hint?.[backend];if(hint){camera.position.fromArray(hint.position);camera.up.fromArray(hint.up);camera.fov=hint.fov||42;camera.near=.001;camera.far=1000;controls.target.fromArray(hint.target);camera.lookAt(controls.target);camera.updateProjectionMatrix();controls.update();return;}camera.up.set(0,1,0);camera.fov=42;let box=new THREE.Box3().setFromObject(object),c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),d=Math.max(size.x,size.y,size.z,.1);camera.position.copy(c).add(new THREE.Vector3(d,d*.75,d));camera.near=d/1000;camera.far=d*100;camera.updateProjectionMatrix();controls.target.copy(c);controls.update();home={c,d}}
 reset.onclick=fit;
 function modelEntry(){let key=scene.id+'/'+variant.id;return models?.[key]||models?.[scene.id]?.[variant.id]||models?.[scene.id]}function modelPath(){let v=modelEntry()?.[backend];return typeof v==='string'?v:v?.url||v?.path}
 function loadModel(){if(!inView){needsModel=true;return;}let token=++generation;Object.entries(modelButtons).forEach(([k,b])=>b.setAttribute('aria-pressed',String(k===backend)));if(object){worldScene.remove(object);object.traverse(o=>{o.geometry?.dispose();let ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m){Object.values(m).forEach(t=>{if(t?.isTexture)t.dispose()});m.dispose()}})});object=null}let path=modelPath();status.hidden=false;status.textContent=path?'Loading 3D scene…':'3D asset is being prepared';if(!path||!renderer)return;loadCompressedModel(path,g=>{if(token!==generation)return;object=g.scene;worldScene.add(object);fit();renderDirty=true;status.hidden=true},()=>{if(token===generation)status.textContent='3D asset could not load. Please reload from the local web server.'})}
 let videos=[];const kinds=['real','blender','mujoco'],rgbLabels={real:'Real RGB',blender:'Blender RGB',mujoco:'MuJoCo RGB'};
 function loadVideos(at=0){videos.forEach(v=>v.pause());videos=[];cams.replaceChildren();const views=variant.views||[];cameraIndex=Math.min(cameraIndex,Math.max(0,views.length-1));mode.replaceChildren();views.forEach((view,i)=>{let o=el('option','',view.label||view.id);o.value=String(i);mode.append(o)});mode.value=String(cameraIndex);mode.disabled=!views.length;const view=views[cameraIndex];const ids=[active,...kinds.map((_,i)=>i).filter(i=>i!==active)];for(const index of ids){const kind=kinds[index],tile=el(index===active?'div':'button','camera-tile '+(index===active?'main-camera':'small-camera'));const m=view?.media?.[kind];tile.append(el('span','camera-label',rgbLabels[kind]));if(m?.url){const v=el('video');v.dataset.modality=kind;v.muted=true;v.playsInline=true;v.preload='metadata';v.src=m.url;v.setAttribute('aria-label',rgbLabels[kind]+' · '+(view.label||view.id));v.onloadedmetadata=()=>{v.currentTime=Math.min(at,Math.max(0,v.duration-.02));if(playing)v.play().catch(()=>{})};v.onerror=()=>tile.append(el('span','media-empty','Video unavailable'));tile.append(v);videos.push(v)}else tile.append(el('div','media-empty','Video not available'));if(index!==active){tile.append(el('span','enlarge-hint','⤢ Click to enlarge'));tile.type='button';tile.setAttribute('aria-label','Enlarge '+rgbLabels[kind]);tile.onclick=()=>{active=index;loadVideos(time)}}cams.append(tile)}range.max=1;clock.textContent='0.0 s';play.disabled=!videos.length;range.disabled=!videos.length;}
 mode.onchange=()=>{cameraIndex=Number(mode.value);loadVideos(time)};play.onclick=()=>{playing=!playing;play.textContent=playing?'Ⅱ Pause':'▶ Play';videos.forEach(v=>playing?v.play().catch(()=>{}):v.pause())};range.oninput=()=>{time=Number(range.value);videos.forEach(v=>{if(Number.isFinite(v.duration))v.currentTime=Math.min(time,v.duration-.01)})};setInterval(()=>{let v=videos.find(x=>x.dataset.modality==='real')||videos[0];if(v&&Number.isFinite(v.duration)){if(!range.matches(':active'))range.value=v.currentTime;time=v.currentTime;range.max=v.duration;clock.textContent=`${time.toFixed(1)} / ${v.duration.toFixed(1)} s`;if(playing){videos.filter(x=>x!==v).forEach(x=>{const drift=time-x.currentTime;if(x.readyState<2||x.seeking||v.seeking)return;if(Math.abs(drift)>.6&&time<x.duration){x.currentTime=time;x.playbackRate=1}else{x.playbackRate=Math.abs(drift)<.02?1:Math.max(.96,Math.min(1.04,1+drift*.3))}});if(v.ended){videos.forEach(x=>{x.currentTime=0;x.play().catch(()=>{})})}}}},150);
 function draw(){title.textContent=(scene.id==='mug_microwave'?'Mug & microwave':scene.id==='pour'?'Pouring':scene.id)+(augmentation?' · '+(variant.label||variant.id.replaceAll('_',' ')):'');prompt.textContent=scene.prompt_en;pick.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===scene.id)));variants.replaceChildren();if(augmentation)for(let v of scene.variants){let b=el('button','',v.label||v.id.replaceAll('_',' '));b.setAttribute('aria-pressed',String(v===variant));b.onclick=()=>{variant=v;active=0;cameraIndex=0;time=0;draw()};variants.append(b)}loadModel();loadVideos(0)}
 for(let s of scenes){let b=el('button','scene-card',s.id==='mug_microwave'?'Mug & microwave':s.id==='pour'?'Pouring':s.id);b.dataset.id=s.id;b.title=s.prompt_en;const thumb=el('img');thumb.src=window.R2G.posters[(augmentation?'02':'01')+'_'+s.id];thumb.alt='';thumb.loading='lazy';thumb.onerror=()=>thumb.remove();b.prepend(thumb);if(augmentation)b.append(el('small','scene-card-prompt',s.prompt_en));b.onclick=()=>{scene=s;variant=s.variants[0];active=0;cameraIndex=0;time=0;draw()};pick.append(b)}draw();new IntersectionObserver(es=>{const visible=es[0].isIntersecting;if(visible!==playing){playing=visible;play.textContent=playing?'Ⅱ Pause':'▶ Play';videos.forEach(v=>playing?v.play().catch(()=>{}):v.pause())}},{threshold:.35}).observe(cams);return {refreshModels(m){models=m;loadModel()}};
}

async function loadCompressedModel(path, onLoad, onError) {
 try {
  const response = await fetch(path);
  if (!response.ok) throw new Error(`Model HTTP ${response.status}`);
  if (!response.body) throw new Error('Model response is empty');
  if (typeof DecompressionStream === 'undefined') throw new Error('Gzip decompression requires a current browser');
  const stream = response.body.pipeThrough(new DecompressionStream('gzip'));
  const buffer = await new Response(stream).arrayBuffer();
  new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parse(buffer, '', onLoad, onError);
 } catch (error) {
  onError(error);
 }
}
